### PR TITLE
Fix for issue #17 throwing an error

### PR DESCRIPTION
**Pull request by yrimal**
Fix for issue #17: 

Currently, a bootstrap sets only a valid BS date and if any invalid date is input, it'll store the previously set date and user won'd know that their input was invalid. This fix will enable bootstrap to pass null if invalid date is inputed by user such that other tools using this component know and handle it correctly.

### CODE REVIEW

**Review by dianabarsan — APPROVED** [review]
Cool stuff, thanks for working on this! 

I believe we also have to bump the version, so we can publish the new release and update webapp to use this new code. Here's an example of this being done before: https://github.com/medic/bikram-sambat/commit/e26bc7646b9a0bfcb8a5ef2f8ac704e5574368e0# 
I can handle the publishing to npm after this is merged.

**Comment by yrimal** [comment]
Hi @dianabarsan , I've changed the version.

**Review by jkuester — COMMENTED** [review]
@yrimal Looking at this from the perspective of the whole `bikram-sambat-datepicker` workflow, how is this going to affect the behavior of that widget?  If I enter an invalid value into the widget on a form and save it, will the form just save an empty value for that date?  Is that the behavior we want?  It does at least make things more consistant in terms of how things will behave when editing required date values (since now an invalid date in a required field will prevent the form from saving).  

I am  just wondering if the `bikram-sambat-datepicker` widget will be able to tell the difference between an empty widget and a widget with an invalid value?  It would be nice to have the widget be able to trip the Enketo constraint logic if an invalid value is entered (similar to what the phone widget does if a phone number fails validation)...

**Comment by yrimal** [comment]
Hi @jkuester , 

>If I enter an invalid value into the widget on a form and save it, will the form just save an empty value for that date?

As you've pointed, If the field is required, it will not accept the form until a valid bikram sambat date is entered and prevent user from saving or moving ahead.

In terms where this field is not required, we'll check if we can add validation like telephone widget.
Or do you think returning `null` when invalid date is given and returning `undefined` when date is untouched would be a good idea ? I can try this option as well.

**Comment by yrimal** [comment]
>Or do you think returning null when invalid date is given and returning undefined when date is untouched would be a good idea ? I can try this option as well.

This could be really difficult to distinguish it however and we can still try it on CHT-Core by overriding enketo validation and hope  that works.

**Comment by jkuester** [comment]
I am not sure if this would end up having unintended side-effects, but one idea I had was updating the [`getDate_greg_text` function](https://github.com/medic/bikram-sambat/blob/3aabed54e2fe3177d02bf41c9358d04845176177/bootstrap/src/bikram-sambat-bootstrap.js#L84) to verify there was a value for the year/month/day before calling `toGreg_text`.  If no values were provided for any of the fields, just return `null`.  If any value was provided, call `toGreg_text`, but don't do it in the try-block. If the values are invalid, `toGreg_text` will throw the error and maybe it can bubble back up to the widget where it can be caught and interpreted as an invalid date.  We would need to do some more investigation around this, though, to make sure it actually would work and would not cause unintended consequences (in the widget or other places where the library is used...).  

Ultimately, I am happy to follow your discretion on this issue.  If you feel that the current change is sufficient and it is a lower priority to alert the user that they entered an invalid date that will not be saved I am absolutely fine with moving ahead with things like they are now in the PR.  We can log a new issue with our thoughts on this extra validation.

**Pull request merged**
