### PR TITLE
fix(#20): fix incorrect days in 2081

### LINKED ISSUE #20: Incorrect daysInMonth data for year 2081
https://github.com/medic/bikram-sambat/blob/c730b3219507f0c2700addd28ffe5308c3e3e2a8/test-data/daysInMonth.json#L113

In Bikram Sambat year 2081:
- 2nd month should have 32 days
- 3rd month should have 31 days

Reference
- https://github.com/opensource-nepal/node-nepali-datetime/pull/79
- https://english.hamropatro.com/calendar/2081/3
- https://english.hamropatro.com/calendar/2081/4

### PR DESCRIPTION
**Pull request by aloundoye**
fix #20

### CODE REVIEW

**Comment by aloundoye** [comment]
Hi @garethbowen, can you help with this PR? I tried to solve the failing test on #25 but still have some issues. I will need your help there, too.

**Comment by garethbowen** [comment]
@aloundoye All the builds are too old so I cannot see why they failed any more. Can you push a change to this branch to kick off the build again and let me know when it fails?

**Comment by aloundoye** [comment]
@garethbowen, for `test java` I fixed it here, #25, but the other tests are not even running it is marked `This job failed`

**Comment by garethbowen** [comment]
Ahh, if you look at the "annotations" for those builds it's because the environment is deprecated:

> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

So there more updates required to even get the action to start running.

**Comment by aloundoye** [comment]
Ah, thanks @garethbowen . I missed that it works now all the tests passed #25

**Review by garethbowen — APPROVED** [review]
Nice one

**Pull request merged**
